version: "3.9" 
services:
  front-end:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - social
  backend:
    build: ./backend
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/social
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - social
  socker-server:
    build: ./socket-server
    ports:
      - "5500:5500"
    networks:
      - social
  mongo-db:
    image: mongo
    networks:
      - social
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - social
networks:
  social:
